version: '3.10'
services:
  app:
    image: reminders
    ports:
      - "8081:1337"
    links:
      - redis
    restart: always
  redis:
    image: redis
    restart: always
    container_name: redis
    working_dir: /opt
    ports:
      - "6379:6379"
